### ISSUE TITLE
Some repeatable events occur even when they are already cancelled

### ISSUE THREAD

**Issue by gelin** [gelin/calendar-bot#30]
Hard to reproduce but happened multiple times with this calendar:
https://calendar.google.com/calendar/ical/aqclsibjm591jbbk875uio9k40%40group.calendar.google.com/public/basic.ics (Omsk IT Events)

**Comment by Colbys** [comment]
Steps to reproduce:
1. Set advance hours to "24 12 6 3 1" (values are not important, but they're here for the reference).
2. Create repeatable event (for example, repeats every Mon-Fri). Important note - the second event should be a little bit farther than the largest advanced value (i.e. if your largest advance value is 24, then it should be at least 24:05, so that it won't be triggered from the start).
3. Reschedule the second event in a way that it would be before the second advance value (in this case, 12:05). Depending on how long it takes for the bot to check events (set by `interval` value in bot config), bot may post this event to the chat.
4. Wait until it will be the time for the bot to post event that was scheduled 24 hours in advance

**Comment by gelin** [comment]
Should be fixed by https://github.com/gelin/calendar-bot/pull/33
